version: '3.6'
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    command: npm run start:debug
    env_file:
      - .env
    networks:
      - nestmongo
    depends_on:
      - mongodb-primary

  mongodb-primary:
    container_name: mongodb-primary
    image: docker.io/bitnami/mongodb:6.0
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_USER=root
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    volumes:
      - .:/bitnami/mongodb
    networks:
      - nestmongo
    ports:
      - 27017:27017
networks:
  nestmongo:
    driver: bridge
