version: '3.5'

services:
  app:
    container_name: nestapp
    build:
      context: ./docker
      dockerfile: Dockerfile
    working_dir: /var/www/school
    ports:
      - 3000:80
    env_file:
      - .env
    networks:
      - schoolnet
    volumes:
      - .:/var/www/school

networks:
  schoolnet:
    driver: bridge
